### ISSUE TITLE
'he' locale message missing closing bracket '}'

### ISSUE THREAD

**Issue by lielvan** [larryaasen/upgrader#236]
```
I/flutter (18122): upgrader: languageCode: he
I/flutter (18122): upgrader: operatingSystem: android
I/flutter (18122): upgrader: platform: TargetPlatform.android
I/flutter (18122): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (18122): upgrader: package info version: 3.7.71
I/flutter (18122): upgrader: countryCode: US
I/flutter (18122): upgrader: languageCode: en
Reloaded 1 of 2735 libraries in 439ms (compile: 37 ms, reload: 213 ms, reassemble: 171 ms).
I/flutter (18122): upgrader: blocked: false
I/flutter (18122): upgrader: debugDisplayAlways: true
I/flutter (18122): upgrader: debugDisplayOnce: false
I/flutter (18122): upgrader: hasAlerted: false
I/flutter (18122): upgrader: shouldDisplayUpgrade: true
I/flutter (18122): UpgradeCard: will display
I/flutter (18122): UpgradeCard: showDialog title: לעדכן יישומון?
I/flutter (18122): UpgradeCard: showDialog message: גרסה חדשה של קיימת! גרסה 3.7.68 ניתנת להורדה-יש לך גרסה {{currentInstalledVersion}.
```
```
  upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.11.0"
```

Seems the case for `'he'` locale is missing a closing bracket for the variable  `currentInstalledVersion` in upgrade_messages.dart line 150.
