### ISSUE TITLE
BUG - Stream event not catch  

### ISSUE THREAD

**Issue by Clement-Marchais-Wiztivi** [larryaasen/upgrader#350]
## Description 
I'm currently facing some problem on the new `evaluationStream`. I'm using appcast file and the widget `UpgradeAlert` don't always receive the new boolean `UpgraderEvaluateNeed`. 

Does anyone have the same problem ?? 

## Implementation

```
return UpgradeAlert(
      navigatorKey: navigatorStateKey,
      upgrader: Upgrader(
        appcastConfig: AppcastConfiguration(
          url: 'link',
          supportedOS: ['android'],
        ),
        debugLogging: true,
        debugDisplayAlways: true,
        durationUntilAlertAgain: Duration.zero,
      ),
      child: child,
    );
````
In the build of `UpgradeAlert` widget , the streamBuilder don't seem to receive the last value of `evaluationStream`. First value received is false, the one by default but in the function `initialize` of the `Upgrader` class if the streamController emit a new value true the streamBuilder is not update and don't check the version 
 
## Additional information 

```
I/flutter ( 3703): upgrader: instantiated.
I/flutter ( 3703): upgrader: initialize called
I/flutter ( 3703): upgrader: build UpgradeAlert
I/flutter ( 3703): upgrader: initializing
I/flutter ( 3703): upgrader: languageCode: en
I/flutter ( 3703): upgrader: default operatingSystem: android XX
I/flutter ( 3703): upgrader: operatingSystem: android
I/flutter ( 3703): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter ( 3703): upgrader: package info packageName: XX
I/flutter ( 3703): upgrader: package info appName: XX
I/flutter ( 3703): upgrader: package info version: 1.8.0
I/flutter ( 3703): upgrader: instantiated.
I/flutter ( 3703): upgrader: build UpgradeAlert
I/flutter ( 3703): upgrader: appcast item count: 1
I/flutter ( 3703): upgrader: appcast best item version: 1.8.1
I/flutter ( 3703): upgrader: appcast critical update item version: null
```

```
   upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      sha256: "889c1ece7af143df32e8ee2126f2ef17b2ab6bb7ed8fc3b1b022d7faa4fdab20"
      url: "https://pub.dev"
    source: hosted
    version: "8.2.0"
```
