### ISSUE TITLE
Can't find an app in the Play Store

### ISSUE THREAD

**Issue by NaveenKris** [larryaasen/upgrader#492]
Currently in playstore, I have version 1.0.27 with description [Minimum supported app version: 1.0.27] under only for our Organization (domain) not public. I added the upgrader log and pubspec.lock details below:

Upgrader Log:
```
I/flutter (17212): upgrader: instantiated
I/flutter (17212): upgrader: initialize called
I/flutter (17212): upgrader: build UpgradeAlert
I/flutter (17212): upgrader: initializing
I/flutter (17212): upgrader: operatingSystem: android, version: UP1A.231005.007.A145FXXS9CYB1
I/flutter (17212): upgrader: packageInfo packageName: org.newincentives.abae_id_validation
I/flutter (17212): upgrader: packageInfo appName: ABAE ID Validation
I/flutter (17212): upgrader: packageInfo version: 1.0.26
I/flutter (17212): upgrader: current locale: en_GB
I/flutter (17212): upgrader: countryCode: GB
I/flutter (17212): upgrader: languageCode: en
I/flutter (17212): upgrader: lookupById url: https://play.google.com/store/apps/details?id=org.newincentives.abae_id_validation&gl=GB&hl=en&_cb=1742457422854574
I/flutter (17212): upgrader: Can't find an app in the Play Store with the id: org.newincentives.abae_id_validation
I/flutter (17212): upgrader: UpgraderPlayStore: version info: appStoreListingURL: null, appStoreVersion: null, installedVersion: 1.0.26, isCriticalUpdate: null, minAppVersion: null, releaseNotes: null
I/flutter (17212): upgrader: need to evaluate version
I/flutter (17212): upgrader: blocked: false
I/flutter (17212): upgrader: debugDisplayAlways: false
I/flutter (17212): upgrader: debugDisplayOnce: false
I/flutter (17212): upgrader: hasAlerted: false
I/flutter (17212): upgrader: installedVersion: 1.0.26
I/flutter (17212): upgrader: minAppVersion: null
I/flutter (17212): upgrader: isUpdateAvailable: false
I/flutter (17212): upgrader: shouldDisplayUpgrade: false
I/flutter (17212): upgrader: shouldDisplayReleaseNotes: false
```
 pubspec.lock file:
```
  upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      sha256: eb5a4888873d7998605306c4212491efdff8e59ee609d946dbcd6df83598d004
      url: "https://pub.dev"
    source: hosted
    version: "11.3.1"
```
